flutter_launcher_icons:

  android: true

  ios: false

  min_sdk_android: 21

  image_path: assets/icon/app_icon.png

  adaptive_icon_background: "#87CEEB"

  adaptive_icon_foreground: assets/icon/app_icon.png