flutter_launcher_icons:
  android: true
  ios: false

  image_path: assets/icon/app_icon.png

  adaptive_icon_background: "#87CEEB"
  adaptive_icon_foreground: assets/icon/app_icon.png

flutter_native_splash:
  android: true
  ios: false

  background_image: assets/images/background/home_background.png
  image: assets/icon/app_icon.png

  android_12:
    background_image: assets/images/background/home_background.png
    image: assets/icon/app_icon.png

  fullscreen: true