workflows:
  android-workflow:
    name: Puzzle World Android Release

    environment:
      flutter: stable

    scripts:

      - name: Remove old pub cache
        script: |
          rm -rf ~/.pub-cache/hosted/pub.dev/google_mobile_ads-5.3.1
          rm -f pubspec.lock

      - name: Get packages
        script: |
          flutter pub get
          flutter pub deps | grep google_mobile_ads

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk