name: Encode Release Keystore

on:
  workflow_dispatch:

jobs:
  encode:
    runs-on: ubuntu-latest

    steps:
      - name: Create temporary folder
        run: mkdir -p keystore_input

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: keystore-input
          path: keystore_input