name: Flutter Android Build

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.8'
          channel: stable


      - name: Check pubspec.yaml
        run: |
          pwd
          ls -la
          echo "===================="
          sed -n '1,120p' pubspec.yaml
          echo "===================="


      - name: Flutter pub get
        run: flutter pub get


      - name: Check Unity Ads version
        run: flutter pub deps | grep unity_ads_plugin


      - name: Fix Unity Ads Java Compatibility
        run: |
          UNITY_DIR=$(find ~/.pub-cache/hosted/pub.dev -maxdepth 1 -type d -name "unity_ads_plugin-*" | head -1)

          echo "Unity Ads directory:"
          echo "$UNITY_DIR"

          if [ -d "$UNITY_DIR/android" ]; then
            echo "Patching Unity Ads..."

            cat <<EOF >> "$UNITY_DIR/android/build.gradle"

android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "17"
    }
}
EOF

            echo "Unity Ads patched successfully"
          else
            echo "Unity Ads plugin not found"
            exit 1
          fi


      - name: Generate App Icon
        run: dart run flutter_launcher_icons


      - name: Build APK
        run: flutter build apk --release


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: puzzle-world-apk
          path: build/app/outputs/flutter-apk/app-release.apk